add docker credentials.

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -38,8 +38,9 @@ jobs:
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
       # Build Docker image
-      - name: Build Docker image
-        run: docker buildx build -f docker/Dockerfile -t gcr.io/beckendtest/finone-backend:${{ github.sha }} .
+      - name: Verify Docker image exists
+        run: |
+          docker images | grep gcr.io/beckendtest/finone-backend:${{ github.sha }} || echo "Docker image not found"
 
       # Check if Docker image exists
       - name: Check if Docker image exists
